fuz_quickstart:
    resource: "@FuzQuickStartBundle/Resources/config/routing.yml"

app:
    resource: "@FuzAppBundle/Controller/"
    type:     "annotation"
    prefix:   /

app_options:
    resource: "@FuzAppBundle/Controller/Options/"
    type:     "annotation"
    prefix:   /
